# FROM tells Docker what environment to build the app on top of
# 'slim' images are used when you only want the necessary files/libraries for your app to be able to run
FROM openjdk:11-jdk-slim

# COPY tells Docker what files/directories to save into the container, and allows renaming of those files/directories
# left side is directory location of file to copy, right side after space is the new copied file renamed
COPY  target/boot-0.0.1-SNAPSHOT.jar app.jar

# ENTRYPOINT tells Docker what command to run to starup the app
# Need to put individual commands as String as demonstrated below
ENTRYPOINT ["java", "-jar", "app.jar"]

# To build the image, use the command: docker build  and then the location of the dockerfile
# If the dockerfile is in the working directory, just use a .
# Use the -t flag to name the image

# to run it, (docker run sports -p 8080:8080)